#!/usr/bin/env bash

if pacman -Qs ufw &>/dev/null; then
  systemctl enable ufw
  ufw default deny incoming
  ufw default allow outgoing
  ufw enable

  if pacman -Qq kdeconnect > /dev/null ; then
    ufw allow "KDE Connect"
  fi

fi
