#!/bin/bash

_check_nvidia_card="$(chwd --is_nvidia_card | grep -q 'NVIDIA card found!'; echo $?)"

if [[ "${_check_nvidia_card}" -eq 0 ]]; then
  echo "NVIDIA CARD FOUND!"
  chwd --ai_sdk -a pci nonfree 0300

  # Check for hybrid graphics
  if [[ $(lspci -d "*:*:0302") ]]; then
    chwd --ai_sdk -a pci nonfree 0302
  fi
fi


# vim:set ft=bash sw=2 sts=2 et:
