# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the welcomeq module (online variant).
#
# The configuration for welcomeq is exactly the same
# as the welcome module, with the one exception of
# *qmlSearch* which governs QML loading.
#
# No documentation is given here: look in the welcome module.
---
# Setting for QML loading: use QRC, branding, or both sources of files
qmlSearch: both

showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    8.0
    requiredRam:        2.5
    internetCheckUrl:   https://wiki.cachyos.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        # - storage
        - ram
        # - root
        - internet

geoip:
    style:    "xml"
    url:      "https://geoip.kde.org/v1/ubiquity"  # extended XML format
    selector: "CountryCode"  # blank uses default, which is wrong
