# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the one-user-system user module (QML variant).
#
# For documentation see Users Module users.conf
#
---
defaultGroups:
    - wheel
    - rfkill
    - sys
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio
    - name: nopasswdlogin
      must_exist: false
      system: true

doAutologin:     false

sudoersGroup:    wheel

setRootPassword: true

doReusePassword: true

passwordRequirements:
#    nonempty: true
    minLength: 4
#    maxLength: -1  # Password at most this many characters
#    libpwquality:
#        - minlen=0
#        - minclass=0

allowWeakPasswords: false
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root ]
  home_permissions: "o700"
  nopasswd_group: "nopasswdlogin"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "cachyos-${cpu}"
  forbidden_names: [ localhost ]

# Enable Active Directory enrollment support (opt-in)
allowActiveDirectory: false

presets:
    fullName:
        # value: "OEM User"
        editable: true
    loginName:
        # value: "oem"
        editable: true
