# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Remove empty installer directories left after post-install scripts are deleted.
---

dontChroot: false
timeout: 10
script:
    - "-rmdir /etc/calamares/scripts"
    - "-rmdir /etc/calamares"

i18n:
    name: "Removing installer files from target system"
